security:

  providers:
    from_database:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    login:
      pattern: ^/login$
      anonymous: true
    api:
      pattern: ^/api/
      anonymous: true
    main:
      pattern: ^/
      anonymous: false
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path: logout
        target: login

  encoders:
    App\Entity\User:
      algorithm: bcrypt
      cost: 12